### ISSUE TITLE
你是魔鬼吗?

### ISSUE THREAD

**Issue by FalleverX** [dploop/leetcode#1]
![img](https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1551110118824&di=6eba8696196189e03056ed88ccacfbb5&imgtype=0&src=http%3A%2F%2Fb-ssl.duitang.com%2Fuploads%2Fitem%2F201804%2F21%2F20180421185837_hdkke.jpg)

**Comment by rbee3u** [comment]
大佬游戏做得怎么样了？

**Comment by FalleverX** [comment]
感觉才过狮驼岭,要取真经还早哩
😢 😢
